#开发配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/ziyu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.xk.ziyu.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#端口号
server:
  port: 9988

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 配置本地静态图片资源访问
spring.mvc.static-path-pattern: /images/**
spring.resources.static-locations: file:F://zige/images/
